sudo: false
language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
env:
  global:
    - MAGEDB_DBHOST=localhost
    - MAGEDB_DBUSER=root
    - MAGEDB_DBPASS=root
    - MAGEDB_DBNAME=magento_demo
    - MAGEDB_SAMPLEDATA=no
    - MAGE_BASEURL=http://magento-demo.com
script:
  - curl -sSL https://raw.githubusercontent.com/pipe-devnull/compose-mage/pdn_alerts/remote-install.sh | bash
